name: Create Tag and Release

on:
  push:
    branches:
      - main  # Change this to the desired branch name

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo-2
      uses: actions/checkout@v2
      with:
        repository: <repo-2-owner>/<repo-2-name>
        ref: main  # Change this to the desired branch name

    - name: Create Tag and Release
      run: |
        pwd
        ls
        # Get the generic token from the secrets
        GENERIC_TOKEN=$GENERIC_TOKEN

        # Replace with your GitHub API endpoint and repo-2 information
        REPO_2_OWNER=primeap
        REPO_2_NAME=poc-2
        NEW_TAG_NAME=v1.0.0  # Change this to the desired tag name

        # Create a tag using GitHub API
        curl -X POST \
          -H "Authorization: token $GENERIC_TOKEN" \
          -d '{
            "tag": "$NEW_TAG_NAME",
            "message": "Tag $NEW_TAG_NAME",
            "object": "main",
            "type": "commit",
            "tagger": {
              "name": "Your Name",
              "email": "your.email@example.com",
              "date": "YYYY-MM-DDTHH:MM:SSZ"
            }
          }' \
          "https://api.github.com/repos/$REPO_2_OWNER/$REPO_2_NAME/git/tags"

        # Create a reference to the tag
        curl -X POST \
          -H "Authorization: token $GENERIC_TOKEN" \
          -d '{
            "ref": "refs/tags/$NEW_TAG_NAME",
            "sha": "$NEW_TAG_SHA"
          }' \
          "https://api.github.com/repos/$REPO_2_OWNER/$REPO_2_NAME/git/refs"
      env:
        GENERIC_TOKEN: ${{ secrets.GENERIC_TOKEN }}
